chore: dismiss all before returning home
getAlby/go pull request #227
Opened 2024-12-18 16:28 UTC by im-adithya

## Screenshots

<table><tr><td>
<img src="https://github.com/user-attachments/assets/2590f3f4-3774-4ac0-be69-2dbd3424779c"/>
</td><td>
<img src="https://github.com/user-attachments/assets/87ccb30e-9b9e-4cf4-b395-9adbb48fbd71"/>
</td></tr></table>

Note: for some reason, this cannot be observed in Expo Go but the production build also has this issue.

2024-12-20 05:35 UTC, rolznz approved these changes
utACK

2024-12-20 05:35 UTC, rolznz commented on pages/settings/wallets/SetupWallet.tsx
> +    router.navigate("/");
is this navigation even needed if we dismiss all the routes? shouldn't this be the default?

2024-12-20 05:36 UTC, rolznz commented on pages/settings/wallets/SetupWallet.tsx
> +    router.navigate("/");
Won't this also push a route onto the stack, leaving a back button?

2024-12-20 05:36 UTC, rolznz requested changes
EDIT: please check comments

2024-12-23 19:17 UTC, im-adithya commented
Addressed, should be good now!

2024-12-24 12:55 UTC, merged